### ISSUE TITLE
Kafka Cloudant Connect keeps giving timeout when more than 1 pod in the cluster

### ISSUE THREAD

**Issue by moisescastellano** [IBM/cloudant-kafka-connector#90] opened 2022-08-30 10:00 UTC
Hi:

Our architecture needs a Kafka connector that provisions a topic when there are changes in Cloudant, we had also to (in real time) create that connector when the user logs in for the first time. 

We have been able to create the Kafka Connectors via the Kafka Connect REST API (https://docs.confluent.io/platform/current/connect/references/restapi.html),
however it randomly fails and provides "java.net.SocketTimeoutException: Connect Timeout".

Even worst, after the first fail it behaves badly providing the SocketTimeoutException to subsequent POST creation requests,
even when Kafka Connect API is up and responding ok to e.g. GET connectors requests.

We have been googling this issue ("SocketTimeoutException kafka connect api") and a few people got it but a clear solution is not available beyond obvious ones like changing timeouts.

Most of this issue has been temporarily resolved by downloading the replicas of the Kafka cluster (Kafka Connect pods) from 3 to 1 - so this seems like a problem with balancing - however this is not ok for Prod environment and we are still searching for trhe root cause.

The POST request to the Kafka Connect API:
{
    "name": "xxxxxxxxxxx",
    "config": {
        "connector.class": "com.ibm.cloudant.kafka.connect.CloudantSourceConnector",
        "cloudant.db.url": "https://xxxxxxxxxx.cloudantnosqldb.appdomain.cloud/xxxxxxxxx",
        "cloudant.db.username": "xxxxxxxxxxxx",
        "cloudant.db.password": "xxxxxxxxxxxx",
        "topics": "mapis-dev-cloudant-test-provisioning-connector",
        "connection.timeout.ms": 5000,
        "read.timeout.ms": 5000
       }
  }

Our code is just creating the previous request:

            URL apiUrl = new URL(kafkaConnectApiUrl.get());
            HttpsURLConnection http = (HttpsURLConnection)apiUrl.openConnection();
            http.setRequestMethod("POST");
            http.setDoOutput(true);
            http.setRequestProperty("Accept", "application/json");
            http.setRequestProperty("Content-Type", "application/json");

            String data = "{\n  \"name\": \"" + dbName + "\""
                        + ",\n  \"config\": {"
                              + "\n \t \"connector.class\": \"com.ibm.cloudant.kafka.connect.CloudantSourceConnector\""
                              + ",\n \t \"cloudant.db.url\": \"" + cloudantUrl.get() + "/" + dbName + "\""
                              + ",\n \t \"cloudant.db.username\": \"" + username.get() + "\""
                              + ",\n \t \"cloudant.db.password\": \"" + password.get() + "\""
                              + ",\n \t \"topics\": \"" + kafkaTopic.get() + "\""
                              + ",\n \t \"connection.timeout.ms\": 5000"
                              + ",\n \t \"read.timeout.ms\": 5000"
                        + "\n \t}"
                        + "\n}"
                        ;
      
            byte[] out = data.getBytes(StandardCharsets.UTF_8);
      
            OutputStream stream = http.getOutputStream();
            stream.write(out);
            stream.flush();
            stream.close();
	        int responseCode = http.getResponseCode();
            http.disconnect();

**Comment by ricellis** [comment] 2022-08-30 10:36
To help us resolve your issue please provide the stack trace of the `SocketTimeoutException` and the environment details requested in the GitHub issue template:

## Environment details
- Version(s) that are affected by this issue.
    > 
- Java version including vendor and platform
    > 
- Apache Kafka versions (including Scala and any vendor or platform info)
    > 

Thanks

**Comment by moisescastellano** [comment] 2022-08-30 11:18
Hi Ricellis:

Environment is Openshift - Kubernetes version v1.21.11+6b3cbdd

Operator: Strimzi	0.22.1 provided by Strimzi

Kafka vesion: 2.6.0

java -version:
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9-LTS, mixed mode, sharing)

Stack trace:

2022-08-22 08:12:16,672 INFO SourceConnectorConfig values:
        config.action.reload = restart
        connector.class = com.ibm.cloudant.kafka.connect.CloudantSourceConnector
        errors.log.enable = false
        errors.log.include.messages = false
        errors.retry.delay.max.ms = 60000
        errors.retry.timeout = 0
        errors.tolerance = none
        header.converter = null
        key.converter = null
        name = a001011511v43
        predicates = []
        tasks.max = 1
        topic.creation.groups = []
        transforms = []
        value.converter = null
 (org.apache.kafka.connect.runtime.SourceConnectorConfig) [DistributedHerder-connect-1-1]
2022-08-22 08:12:16,675 INFO EnrichedConnectorConfig values:
        config.action.reload = restart
        connector.class = com.ibm.cloudant.kafka.connect.CloudantSourceConnector
        errors.log.enable = false
        errors.log.include.messages = false
        errors.retry.delay.max.ms = 60000
        errors.retry.timeout = 0
        errors.tolerance = none
        header.converter = null
        key.converter = null
        name = a001011511v43
        predicates = []
        tasks.max = 1
        topic.creation.groups = []
        transforms = []
        value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig) [DistributedHerder-connect-1-1]
2022-08-22 08:12:31,717 ERROR IO error forwarding REST request:  (org.apache.kafka.connect.runtime.rest.RestClient) [ForwardRequestExecutor-connect-1-1]
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:711)
        at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:125)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$reconfigureConnector$6(DistributedHerder.java:1456)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.io.ManagedSelector$Connect.run(ManagedSelector.java:812)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        ... 3 more
2022-08-22 08:12:31,720 ERROR [Worker clientId=connect-1, groupId=dev-connect-cluster-group] Request to leader to reconfigure connector tasks failed (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [ForwardRequestExecutor-connect-1-1]
org.apache.kafka.connect.runtime.rest.errors.ConnectRestException: IO Error trying to forward REST request: java.net.SocketTimeoutException: Connect Timeout
        at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:144)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$reconfigureConnector$6(DistributedHerder.java:1456)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:711)
        at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:125)
        ... 6 more
Caused by: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.io.ManagedSelector$Connect.run(ManagedSelector.java:812)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        ... 3 more
2022-08-22 08:12:31,722 ERROR [Worker clientId=connect-1, groupId=dev-connect-cluster-group] Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [ForwardRequestExecutor-connect-1-1]
org.apache.kafka.connect.runtime.rest.errors.ConnectRestException: IO Error trying to forward REST request: java.net.SocketTimeoutException: Connect Timeout
        at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:144)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$reconfigureConnector$6(DistributedHerder.java:1456)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:711)
        at org.apache.kafka.connect.runtime.rest.RestClient.httpRequest(RestClient.java:125)
        ... 6 more
Caused by: java.net.SocketTimeoutException: Connect Timeout
        at org.eclipse.jetty.io.ManagedSelector$Connect.run(ManagedSelector.java:812)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        ... 3 more

Thanks
Regards
Moises

**Comment by ricellis** [comment] 2022-08-30 14:36
To me that looks more like a network problem for the Kafka cluster, rather than something specific to the Cloudant connector.

I think the problem is that the Kafka REST client on the worker that received the request is unable to forward the configuration request to the leader.
The success cases you are seeeing are probably when the REST request reaches the leader first. In the case you scale back to 1 from 3 then the only worker is also the leader.

I think the best advice I can offer is to check that the clsuter networking is configured such that all the worker nodes can reach each other with requests. It seems like the sort of thing strimzi should be able to configure, but I'm not familiar with it so I can't help you there. There is a similar [question here](https://stackoverflow.com/questions/61414970/only-one-node-of-a-kafka-connect-cluster-responds-to-rest-api-requests) for a Docker setup.

You might also be able to get more information from the error response by tweaking your REST request code to get the error stream from your REST request e.g.

```java
        try {
            try(OutputStream outStream = http.getOutputStream()) {
                outStream.write(out);
                outStream.flush();
            }
            InputStream inStream = null;
            int responseCode = http.getResponseCode();
            if (responseCode >= HttpURLConnection.HTTP_BAD_REQUEST) {
                // 4xx and 5xx codes
                inStream = http.getErrorStream();
            } else {
                inStream = http.getInputStream();
            }
            try(InputStream responseStream = inStream) {
                String response = new String(responseStream.readAllBytes(), StandardCharsets.UTF_8);
                // TODO log response code and message
            }
        } finally {
            http.disconnect();
        }
```

**Comment by moisescastellano** [comment] 2022-08-31 08:04
Hi Ricellis:

We had already read the input/error stream, no useful info there :-(

I agree the problem could be the communication between workers, we are checking the cluster config.
However if that is the case, it is strange that once the first request fails, any subsequent request also fails. Maybe some type of affinity between the client sending the request and the specific pod?

Thanks
Regards
Moises

**Comment by ricellis** [comment] 2022-08-31 09:27
>We had already read the input/error stream, no useful info there :-(

ah well :(

>Maybe some type of affinity between the client sending the request and the specific pod?

Seems likely. Could be influenced by the type of load balancing you are doing to the REST API. TCP connections are probably persistent when using `HttpURLConnection` so I wouldn't be surprised if any L4 balancing stayed with the same destination.

Might be worth checking the ingress policies for the worker pods - maybe they each need to allow connections to their REST API from the other workers in a distributed setup?

**Comment by ricellis** [comment] 2022-09-16 15:32
I'm going to close this, there is nothing we can do in the Cloudant connector to solve this.

**Closed by ricellis** 2022-09-16 15:32 UTC
